"""Project scaffolder exposed as the ``mosaic-admin`` console script.

    mosaic-admin init [directory]

Generates a complete, runnable flat Django project preconfigured for mosaic:
manage.py, settings.py (the maintained reference config), urls.py, wsgi.py,
asgi.py, a .env, and starter template overrides. This is what the shipped
settings header means by "generated by the mosaic init command".

Bootstrapping a project can't be a management command (that needs settings to
already exist), so it lives here as a standalone entry point instead.
"""

import argparse
import os
import sys
from pathlib import Path

CONF = Path(__file__).resolve().parent / "conf" / "init"

MANAGE_PY = '''#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
'''

URLS_PY = '''"""Root URL configuration."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # Uncomment after adding "django_mosaic.atproto" to INSTALLED_APPS to
    # enable the ATProto bridge's well-known and lexicon-page routes. Keep it
    # before the mosaic include so its root-level paths win.
    # path("", include("django_mosaic.atproto.urls")),
    path("", include("django_mosaic.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

WSGI_PY = '''"""WSGI config."""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
application = get_wsgi_application()
'''

ASGI_PY = '''"""ASGI config."""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
application = get_asgi_application()
'''


def _write(path, content, force):
    if path.exists() and not force:
        print(f"  skip (exists): {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote: {path}")


def init(target, force=False):
    target = Path(target).resolve()
    target.mkdir(parents=True, exist_ok=True)
    print(f"Scaffolding mosaic project in {target}")

    _write(target / "manage.py", MANAGE_PY, force)
    _write(target / "urls.py", URLS_PY, force)
    _write(target / "wsgi.py", WSGI_PY, force)
    _write(target / "asgi.py", ASGI_PY, force)
    _write(target / "settings.py", (CONF / "settings.py").read_text(), force)

    env_src = CONF / ".env.local"
    if env_src.exists():
        _write(target / ".env", env_src.read_text(), force)

    for name in ("header.html", "about.html"):
        src = CONF / "templates" / name
        if src.exists():
            _write(target / "templates" / "includes" / name, src.read_text(), force)

    # Static/media roots referenced by settings; keep them present so the
    # staticfiles check and MEDIA uploads have somewhere to land.
    (target / "static").mkdir(exist_ok=True)
    (target / "media").mkdir(exist_ok=True)

    os.chmod(target / "manage.py", 0o755)

    print(
        "\nDone. Next steps:\n"
        f"  cd {target}\n"
        "  python manage.py migrate\n"
        "  python manage.py createsuperuser\n"
        "  python manage.py runserver\n"
    )


def main(argv=None):
    parser = argparse.ArgumentParser(prog="mosaic-admin")
    sub = parser.add_subparsers(dest="command", required=True)
    init_parser = sub.add_parser("init", help="Scaffold a new mosaic project")
    init_parser.add_argument(
        "directory", nargs="?", default=".", help="Target directory (default: .)"
    )
    init_parser.add_argument(
        "--force", action="store_true", help="Overwrite existing files"
    )
    args = parser.parse_args(argv)

    if args.command == "init":
        init(args.directory, force=args.force)
    return 0


if __name__ == "__main__":
    sys.exit(main())
