# Generated by Django 6.0.1 on 2026-01-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosaic", "0009_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="mosaic.tag"),
        ),
    ]
