# Generated by Django 6.0.2 on 2026-07-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mosaic_atproto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=320)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contact",), name="unique_waitlist_contact"
                    )
                ],
            },
        ),
    ]
