# Generated by Django 6.0.2 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mosaic_atproto", "0002_waitlistsignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("did", models.CharField(max_length=256, unique=True)),
                ("handle", models.CharField(max_length=256)),
                ("pds_url", models.CharField(max_length=512)),
                ("auth_server", models.CharField(max_length=512)),
                ("token_endpoint", models.CharField(max_length=512)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, default="")),
                ("scope", models.CharField(blank=True, default="", max_length=256)),
                ("dpop_jwk", models.JSONField()),
                (
                    "dpop_pds_nonce",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
