# Generated by Django 6.0.1 on 2026-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial_squashed_0008_alter_tag_name_alter_tag_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True),
        ),
    ]
