# Generated by Django 6.0.2 on 2026-02-13 07:58

import secrets

import django_mosaic.models
from django.db import migrations, models

# The default that 0002 stamped onto every existing row. Any rows still holding
# it are duplicates and must be regenerated *before* the unique constraint is
# added below, or the AlterField fails with an IntegrityError on databases that
# enforce uniqueness at index-creation time (Postgres, MySQL).
HARDCODED_DEFAULT = "5abf335a0aa2420cdecca6f0e53a85d4b3879b0cdb0cea2b43f864fafaed425a"


def regenerate_duplicates(apps, schema_editor):
    Post = apps.get_model("django_mosaic", "Post")
    for post in Post.objects.filter(secret_id=HARDCODED_DEFAULT):
        post.secret_id = secrets.token_hex(32)
        post.save(update_fields=["secret_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("django_mosaic", "0003_alter_post_secret_id"),
    ]

    operations = [
        migrations.RunPython(regenerate_duplicates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="post",
            name="secret_id",
            field=models.CharField(
                default=django_mosaic.models.generate_secret_id,
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=512),
        ),
    ]
