# Generated by Django 6.0.1 on 2026-01-26 08:51

from django.db import migrations, models


def invert_is_draft(apps, schema):
    Post = apps.get_model("mosaic", "Post")
    drafts = Post.objects.filter(is_published=True)
    public = Post.objects.filter(is_published=False)
    drafts.update(is_published=False)
    public.update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ("mosaic", "0010_alter_post_published_at_alter_post_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="is_draft",
            new_name="is_published"
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="mosaic.tag"),
        ),
        migrations.RunPython(invert_is_draft),
    ]
