# Generated by Django 6.0.1 on 2026-02-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosaic", "0014_contentimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentimage",
            name="post",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="mosaic.post"
            ),
            preserve_default=False,
        ),
    ]
