# Generated by Django 6.0.1 on 2026-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosaic", "0015_contentimage_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentimage",
            name="image",
            field=models.ImageField(upload_to="content/images/"),
        ),
        migrations.AlterField(
            model_name="contentimage",
            name="thumb",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="content/images/"
            ),
        ),
    ]
