# Generated by Django 6.0.2 on 2026-07-06 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("did", models.CharField(max_length=256, unique=True)),
                ("handle", models.CharField(max_length=256)),
                (
                    "subdomain",
                    models.SlugField(
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$",
                                "Use 1-63 lowercase letters, digits, or hyphens (no leading/trailing hyphen).",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
