# Generated by Django 6.0.2 on 2026-07-06 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mosaic_hosted", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                max_length=253,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=.{4,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z]{2,}$",
                        "Enter a bare domain name like blog.example.com (lowercase, no scheme or path).",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="domain_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(max_length=2000)),
                (
                    "reporter_contact",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="django_mosaic_hosted.tenant",
                    ),
                ),
            ],
        ),
    ]
