# Generated by Django 6.0.1 on 2026-02-03 15:39

import mosaic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosaic", "0013_add_author_to_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="static/images"),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="static/images",
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=2048)),
                ("alt", models.CharField(blank=True, default="", max_length=2048)),
            ],
        ),
    ]
